   const translations = {
      en: { label: "EN", navHome: "Home", navAbout: "About Me", pageTitle: "Professional Services", pageSubtitle: "High-performance engineering architectures tailored for digital security, performance, and scalability.", footerText: "© 2026 Yerone Esayas. Based in Ethiopia.", titles: ["Frontend Engineering","Backend Integration","Network & Cybersecurity Auditing","Custom Voice & AI Automation"], descs: ["Creating stunning, high-fidelity dark interfaces and responsive fluid layouts. Focused strictly on lightning-fast loading speeds, clean semantic code structures, and intuitive modern interactive UI/UX components.","Architecting robust, scalable server solutions and logical routing structures. Expert configuration for custom user session states, fast JSON data manipulation, secure tracking rules, and API endpoints.","Evaluating infrastructure vulnerability posture through local custom scanning arrays. Designing specialized dashboards to accurately map IP routing tables, track active hardware ports, and protect local operations from information exposure.","Building local execution environments and intelligent automation routines inspired by premium system models. Configured to interface securely using isolated data paths that absolutely prevent unauthorized external leaks."] },
      am: { label: "AM", navHome: "ዋና ገጽ", navAbout: "ስለ እኔ", pageTitle: "የባለሙያ አገልግሎቶች", pageSubtitle: "ለዲጂታል ደህንነት፣ አፈጻጸም እና መስፋፋት ተስማሚ የሆኑ ከፍተኛ ደረጃ የምህንድስና መዋቅሮች።", footerText: "© 2026 ይሮን እሳይያስ። አዲስ አበባ፣ ኢትዮጵያ።", titles: ["የፊት-ለፊት ዌብ ምህንድስና (Frontend)","የጀርባ-መስመር ማዋሃድ (Backend)","የኔትወርክ እና የሳይበር ደህንነት ኦዲት","ብጁ የድምፅ እና የAI አውቶሜሽን"], descs: ["አስደናቂ እና ጥራት ያላቸው የጨለማ ገጽታ (dark mode) በይነገጾችን እና ምላሽ ሰጭ የዌብ እቅዶችን መፍጠር። በፈጣን የመጫኛ ፍጥነት፣ በንፁህ የኮድ መዋቅር እና በሚታወቁ ዘመናዊ መስተጋብሮች ላይ ያተኮረ።","ጠንካራ እና ሊሰፉ የሚችሉ የአገልጋይ (server) መፍትሄዎችን እና ምክንያታዊ የዳሰሳ መዋቅሮችን መገንባት። ለተጠቃሚዎች ክፍለ-ጊዜዎች (sessions)፣ ፈጣን የJSON መረጃ አያያዝ እና ደህንነታቸው የተጠበቁ የኤፒአይ የመጨረሻ ነጥቦችን ማዋቀር።","በልዩ ብጁ የመፈተሻ ዘዴዎች አማካኝነት የመሠረተ-ልማት ተጋላጭነትን መገምገም። የአይፒ (IP) አድራሻዎችን ለመቅረጽ፣ ክፍት የሃርድዌር ፖርቶችን ለመከታተል እና አካባቢያዊ ስራዎችን ከመረጃ መፍሰስ ለመጠበቅ ልዩ ዳሽቦርዶችን መንደፍ።","በከፍተኛ የስርዓት ሞዴሎች የተነደፉ አካባቢያዊ የአፈጻጸም አካባቢዎችን እና ብልጥ አውቶሜሽኖችን መገንባት። ያለምንም ያልተፈቀደ የውጭ መረጃ መፍሰስ ደህንነቱ በተጠበቀ ሁኔታ እንዲገናኝ ተደርጎ የተዋቀረ።"] },
      om: { label: "OM", navHome: "Mana", navAbout: "Waa'ee Koo", pageTitle: "Tajaajila Ogummaa", pageSubtitle: "Madaallii gahumsaa fi eegumsa dijiitaalaaf arkitektshara madaalawaa ta'an.", footerText: "© 2026 Yerone Esayas. Finfinnee, Itiyoophiyaa.", titles: ["Injinaringii Frontend","Dabalata Backend","Odiitii Nageenya Network","AI fi Automation Dhuunfaa"], descs: ["Miidhagina bifa gurraachaa fi unka qulqulluu hojjechuun dandeettii daddafanii fe'amuu fi UI/UX ammayyaa irratti xiyyeeffata.","Furmaata server jabaa, qabiinsa jireenya fayyadamaa (sessions) fi API amansiisaa ijaaruu.","Dandeettii network skaan gochuu, IP fi WiFi sakkatta'anii odeeffannoo eeguu dandeessisu.","Automation dhuunfaa fi AI hojii seeraan eegame dhiyeessuu."] },
      fr: { label: "FR", navHome: "Accueil", navAbout: "À Propos", pageTitle: "Services Professionnels", pageSubtitle: "Architectures d'ingénierie hautes performances adaptées à la sécurité, performance et évolutivité.", footerText: "© 2026 Yerone Esayas.", titles: ["Ingénierie Frontend","Intégration Backend","Audit de Sécurité Réseau","Automatisation & IA Custom"], descs: ["Interfaces sombres haute fidélité fluides et rapides.","Solutions serveurs robustes et gestion de sessions sécurisées.","Évaluation des vulnérabilités réseau et tableaux de bord IP/Ports.","Environnements d'exécution locaux intelligents isolés des fuites."] },
      es: { label: "ES", navHome: "Inicio", navAbout: "Sobre Mí", pageTitle: "Servicios Profesionales", pageSubtitle: "Arquitecturas de ingeniería de alto rendimiento para seguridad y escalabilidad.", footerText: "© 2026 Yerone Esayas.", titles: ["Ingeniería Frontend","Integración Backend","Auditoría de Red y Seguridad","Automatización e IA a Medida"], descs: ["Interfaces oscuras premium orientadas a optimización de carga y UI/UX fluido.","Arquitectura de servidores y enrutamiento lógico con manejo de sesiones.","Mapeo estratégico de infraestructuras locales frente a exposición de datos.","Sistemas automatizados inteligentes con aislamiento estricto de filtraciones."] },
      tr: { label: "TR", navHome: "Anasayfa", navAbout: "Hakkımda", pageTitle: "Profesyonel Hizmetler", pageSubtitle: "Dijital güvenlik, performans ve ölçeklenebilirlik için tasarlanmış yüksek performanslı mimariler.", footerText: "© 2026 Yerone Esayas.", titles: ["Frontend Mühendisliği","Backend Entegrasyonu","Ağ ve Siber Güvenlik Analizi","Özel Yapay Zeka & Otomasyon"], descs: ["Hızlı yüklenen, modern etkileşimli bileşenlere sahip akıcı arayüzler.","Güvenli oturum durumları Dit API uç noktaları içeren kararlı sunucu çözümleri.","IP haritalama ve açık port analizleri içeren siber denetim gösterge panelleri.","Dışarı veri sızmasını tamamen engelleyen yerel yapay zeka entegrasyonları."] },
      nl: { label: "NL", navHome: "Home", navAbout: "Over Mij", pageTitle: "Professionele Diensten", pageSubtitle: "Hoogwaardige engineering-architecturen op maat gemaakt voor digitale veiligheid.", footerText: "© 2026 Yerone Esayas.", titles: ["Frontend Engineering","Backend Integratie","Netwerk & Cybersecurity Auditing","Maatwerk AI & Automatisering"], descs: ["Prachtige dark-theme interfaces met de focus op laadsnelheid en UI/UX.","Schaalbare serveroplossingen met geavanceerd sessiebeheer.","Infrastructuur audits door middel van poort- en IP-mapping.","Lokale automatisering met strikte isolatie tegen datalekken."] },
      zh: { label: "ZH", navHome: "首页", navAbout: "关于我", pageTitle: "专业服务方案", pageSubtitle: "专为数字资产安全、高性能访问与高并发扩展打造的工程架构底座。", footerText: "© 2026 Yerone Esayas. 位于埃塞俄比亚。", titles: ["前端极速工程","后端深层集成","网络与网络安全审计","定制化语音与AI自动化"], descs: ["打造令人惊叹的高保真暗黑交互界面与全流体响应式布局。","构建高内聚低 coupling 的服务器架构与逻辑分发路由体系。","通过本地化定制扫描矩阵评估底层基础设施的整体网络安全态势。","基于完全私有化环境构建安全数据沙箱，从根本上杜绝任何外部未授权信息泄露。"] }
    };

    function toggleLangMenu(e) { e.stopPropagation(); const menu = document.getElementById('langMenuBox'); menu.style.display = menu.style.display === 'block' ? 'none' : 'block'; }
    function selectLanguage(lang) {
      localStorage.setItem('selectedLanguage', lang); document.getElementById('currentLangLabel').innerText = translations[lang].label; document.getElementById('langMenuBox').style.display = 'none';
      document.getElementById('navHome').innerText = translations[lang].navHome; document.getElementById('navAbout').innerText = translations[lang].navAbout;
      document.getElementById('pageTitle').innerText = translations[lang].pageTitle; document.getElementById('pageSubtitle').innerText = translations[lang].pageSubtitle; document.getElementById('footerText').innerText = translations[lang].footerText;
      const t = document.querySelectorAll('.srv-title'); t.forEach((el, i) => { if(translations[lang].titles[i]) el.innerText = translations[lang].titles[i]; });
      const d = document.querySelectorAll('.srv-desc'); d.forEach((el, i) => { if(translations[lang].descs[i]) el.innerText = translations[lang].descs[i]; });
    }
    document.addEventListener('click', () => { document.getElementById('langMenuBox').style.display = 'none'; });
    window.addEventListener('DOMContentLoaded', () => { const savedLang = localStorage.getItem('selectedLanguage') || 'en'; selectLanguage(savedLang); });

    const scene = new THREE.Scene(); const camera = new THREE.PerspectiveCamera(75, window.innerWidth / window.innerHeight, 0.1, 1000);
    const renderer = new THREE.WebGLRenderer({ antialias: false, alpha: true, powerPreference: "high-performance" });
    renderer.setSize(window.innerWidth, window.innerHeight); renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
    document.getElementById('canvas-container').appendChild(renderer.domElement);
    const geo = new THREE.BufferGeometry(); const pos = [];
    for (let i = 0; i < 2000; i++) pos.push(THREE.MathUtils.randFloatSpread(2000), THREE.MathUtils.randFloatSpread(2000), THREE.MathUtils.randFloatSpread(2000));
    geo.setAttribute('position', new THREE.Float32BufferAttribute(pos, 3));
    const parts = new THREE.Points(geo, new THREE.PointsMaterial({ color: 0x6366f1, size: 2.5 })); scene.add(parts); camera.position.z = 800;
    function animate() { requestAnimationFrame(animate); parts.rotation.y += 0.0006; renderer.render(scene, camera); } animate();
    window.addEventListener('resize', () => { camera.aspect = window.innerWidth / window.innerHeight; camera.updateProjectionMatrix(); renderer.setSize(window.innerWidth, window.innerHeight); });